# -*- coding: utf-8 -*-
"""M5_projects.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xE3eO-2ZTJ0q4gmdLrWKjcvasHE7xanw
"""

# Run this first. It takes about 1 minute.
!pip install git+https://github.com/amazon-science/chronos-forecasting.git
!pip install gradio fastapi uvicorn nest-asyncio

import pandas as pd
import zipfile
from google.colab import drive

# 1. Connect to Drive (Click 'Allow' in the popup)
drive.mount('/content/drive')

# 2. Path to your folder
drive_path = '/content/drive/MyDrive/M5_Project/'

# 3. Unzip directly to the new local runtime
with zipfile.ZipFile('/content/sales_train_evaluation.csv.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/')

with zipfile.ZipFile('/content/sell_prices.csv.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/')

# 4. Load the data
sales = pd.read_csv('/content/sales_train_evaluation.csv', nrows=2000)
calendar = pd.read_csv('/content/calendar.csv')
prices = pd.read_csv('/content/sell_prices.csv', nrows=5000)

print("✅ Data is back and unzipped!")

import numpy as np

# 1. Melt Sales
df = pd.melt(sales, id_vars=['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id'],
             var_name='d', value_name='sales')

# 2. Merge Calendar & Prices
df = df.merge(calendar[['d', 'event_name_1', 'wm_yr_wk']], on='d', how='left')
df = df.merge(prices, on=['store_id', 'item_id', 'wm_yr_wk'], how='left')

# 3. Clean up
df['sell_price'] = df['sell_price'].fillna(df.groupby('id')['sell_price'].transform('mean'))
df['is_event'] = df['event_name_1'].notnull().astype(int)

print("✅ Master Table is Re-created and ready for the AI!")

import torch
from chronos import ChronosPipeline

# 1. Load the "Base" version of the model (Free and fast for Colab)
# We use 'cuda' because we turned on the T4 GPU earlier!
pipeline = ChronosPipeline.from_pretrained(
    "amazon/chronos-t5-base",
    device_map="cuda",
    torch_dtype=torch.bfloat16,
)

print("✅ AI Brain Loaded Successfully!")

import torch
from chronos import ChronosPipeline

# 1. Load the "Base" version of the model (Free and fast for Colab)
pipeline = ChronosPipeline.from_pretrained(
    "amazon/chronos-t5-base",
    device_map="cuda",  # This uses the Colab GPU for speed!
    torch_dtype=torch.bfloat16,
)

# 2. Pick one product from your Master Table (e.g., the first item)
# We take the last 100 days of sales to "show" the model the trend
context = torch.tensor(df[df['id'] == df['id'].unique()[0]]['sales'].values[-100:])

# 3. Predict the next 28 days (The standard Amazon planning window)
forecast = pipeline.predict(context, prediction_length=28)

print("Forecast Complete! The 'Brain' has spoken.")

import gradio as gr
import matplotlib.pyplot as plt
import numpy as np

def inventory_engine(product_id, current_stock):
    # 1. Get the history for the selected product (last 100 days)
    context_data = df[df['id'] == product_id]['sales'].values[-100:]
    context_tensor = torch.tensor(context_data)

    # 2. Ask the AI to predict the next 21 days
    forecast = pipeline.predict(context_tensor, prediction_length=21)

    # 3. Calculate the "Risk Zone" (P10, P50, P90)
    low, median, high = np.quantile(forecast[0].numpy(), [0.1, 0.5, 0.9], axis=0)

    # 4. Supply Chain Logic: The Reorder Point (ROP)
    # If high-end demand (P90) over next 7 days > current stock, we need more!
    rop = np.sum(high[:7])

    if current_stock <= 0:
        status = "🔴 OUT OF STOCK"
    elif current_stock <= rop:
        status = f"⚠️ REORDER IMMEDIATELY (Threshold: {int(rop)})"
    else:
        status = "🟢 STOCK HEALTHY"

    # 5. Create the Visualization
    plt.figure(figsize=(10, 4))
    plt.plot(context_data[-30:], label="Past 30 Days Sales", color="black")
    plt.plot(np.arange(30, 51), median, label="Predicted Sales", color="blue")
    plt.fill_between(np.arange(30, 51), low, high, color="blue", alpha=0.2, label="Risk Zone")
    plt.axhline(y=current_stock, color='red', linestyle='--', label="Current Stock Level")
    plt.legend()
    plt.title(f"Inventory Forecast: {product_id}")

    return status, plt.gcf()

# 6. Launch the App with a Public Link
demo = gr.Interface(
    fn=inventory_engine,
    # We show the first 50 unique products in the dropdown
    inputs=[
        gr.Dropdown(choices=list(df['id'].unique()[:50]), label="Select Product"),
        gr.Number(label="Enter Current Warehouse Stock", value=50)
    ],
    outputs=[
        gr.Textbox(label="Action Plan"),
        gr.Plot(label="Demand Visualizer")
    ],
    title="📦 Amazon-Style Stock-Run Engine",
    description="Using Transformer-based AI to prevent out-of-stock events."
)

demo.launch(share=True)

# 1. Define Lead Time (7 days for a supplier to ship to Walmart)
lead_time = 7

def calculate_rop(median_forecast, high_forecast):
    # Expected demand during the time we wait for the truck
    demand_during_lead_time = np.sum(median_forecast[:lead_time])

    # Safety Buffer = (High-end Risk - Average Demand)
    # This protects us if a sudden "Stock Run" happens
    safety_stock = np.sum(high_forecast[:lead_time]) - demand_during_lead_time

    return demand_during_lead_time + safety_stock

print("✅ Day 12 Logic Updated: Lead-Time Demand + Safety Stock.")

import pandas as pd
import numpy as np
import torch

# 1. Re-define the Prediction Logic for the Batch
def get_prediction(product_id):
    # Get last 100 days of sales for context
    data = df[df['id'] == product_id]['sales'].values[-100:]
    context = torch.tensor(data)

    # Run the Chronos Brain (make sure 'pipeline' was loaded in Day 7)
    forecast = pipeline.predict(context, prediction_length=21)

    # Calculate Probabilities
    low, median, high = np.quantile(forecast[0].numpy(), [0.1, 0.5, 0.9], axis=0)
    return data, low, median, high

# 2. Re-define the Reorder Logic (Day 12)
def calculate_rop(median_f, high_f):
    lead_time = 7
    demand_during_lt = np.sum(median_f[:lead_time])
    safety_stock = np.sum(high_f[:lead_time]) - demand_during_lt
    return demand_during_lt + safety_stock

# 3. Run the Batch for 50 Items
print("🚀 Starting Batch Process for 50 items... please wait.")
results = []
top_items = df['id'].unique()[:50]

for item in top_items:
    try:
        history, low, median, high = get_prediction(item)
        rop = calculate_rop(median, high)

        # Simulate a current stock level to test the logic
        current_inv = np.random.randint(10, 100)

        results.append({
            "Product_ID": item,
            "Current_Stock": current_inv,
            "Reorder_Point": int(rop),
            "Status": "🚨 REORDER" if current_inv <= rop else "✅ HEALTHY"
        })
    except Exception as e:
        print(f"Error processing {item}: {e}")

# 4. Save the Final Report
report_df = pd.DataFrame(results)
report_df.to_csv("Amazon_Inventory_Report_2026.csv", index=False)

print("✅ Day 13 Success! Download 'Amazon_Inventory_Report_2026.csv' from your sidebar.")
report_df.head()

with open('requirements.txt', 'w') as f:
    f.write('pandas\nnumpy\ntorch\nchronos-forecasting\ngradio\nfastapi\nmatplotlib')
print("✅ requirements.txt generated!")

import matplotlib.pyplot as plt
# This picks one product and saves the graph as a picture
sample_id = df['id'].unique()[0]
status, fig = inventory_engine(sample_id, current_stock=20)
fig.savefig("ai_forecast_proof.png")
print("✅ Graph saved! Now download it from the folder icon on the left.")